acmsigsoft/EmpiricalStandards

Supplements/InformationVisualization.md
guidelines
- different colors represent data variation
- avoid rotated or vertical text
- colorblind-friendly design
anti-patterns
- using line plots to display unordered variables
=> Update information visualization guidelines

docs/Benchmarking.md
I added a missing line break in the list of desirable attributes
=> Added a missing line break

docs/Benchmarking.md
Added recent paper on "Methodological Principles for Reproducible Performance Evaluation in Cloud Computing" as suggested reading
=> Added suggested reading related to benchmarking

Supplements/ReviewerMisconduct.md
Rephrased small bits of the definition of reviewer misconduct and explicitly mentioned parties that may be affected by it.
=> Small changes to the definition of misconduct

README.md
Fix formatting of references (and add identifiers)
=> Add identifiers and add breaks

Supplements/Glossary.md
=> Glossary – First version

docs/EngineeringResearch.md
Fixed the broken link from EngineeringResearch to Benchmarking
=> Fixed broken link

docs/QuestionnaireSurveys.md
Fixed a broken tag. Capitalization and periods.
=> Polish the footnotes

form_generator/js/read_standards.js
Added a field to the exported checklists with the date and time the checklist was generated. Example:
```
=================
Review Checklist
=================
Generated at: Mon Mar 18 2024, 6:00:00 p.m.
(rest of checklist)
```
=> Added date generated field to exported checklist

tab_03_standards.md
Added heading tags to the table of contents on [this page](https://www2.sigsoft.org/EmpiricalStandards/docs/)
=> Add heading tags to TOC

form_generator/js/read_standards.js
Let the two-phase reviewer share the same functionality as one-phase reviewer
=> Update for Two-phase reviewer

form_generator/js/read_standards.js
The text indicating when a checklist was generated has been updated to Anywhere on Earth (AoE) time and moved below the checklist items.
Old format ----> Generated at: Mon Aug 26 2024, 9:55:00 p.m.
New format ----> Generated: Mon Aug 26 2024, 9:55 AM AoE
=> Change date format in downloaded file

docs/standards/Replication.md, form_generator/css/appearance.css, form_generator/js/read_standards.js
Checklist state is now saved locally so the user can navigate away without losing their progress. A "clear checklist" button has been added to reset progress manually.
Try it here: https://eschltz.github.io/standardstest/form_generator/result.html?standard=General+Standard&role=one-phase-reviewer
=> Add state saving functionality for checklists

form_generator/Checklist.html, form_generator/css/appearance.css, form_generator/index.html, form_generator/js/read_standards.js, form_generator/result.html
Old/redundant code has been removed and styling previously applied using JS has been moved to an external CSS file. These changes will make it easier to work on the major redesigns being planned.
=> Code removal + CSS moved

form_generator/css/appearance.css, form_generator/js/read_standards.js
Fixes the issue causing overly wide location boxes on the presubmission checklist
=> Fix styling issue on presubmission checklist

assets/css/style.scss, form_generator/css/appearance.css, form_generator/css/form_responsive.css, form_generator/result.html
Changed link colour on checklists to a more obvious blue and made some small improvements to responsiveness
=> Minor style fixes on checklists

form_generator/css/appearance.css, form_generator/js/FormValidity.js, form_generator/js/PopulateChecklist.js, form_generator/js/ReadStandards.js, form_generator/js/RequirementsChecklist.js, form_generator/js/UIInteractionHandlers.js
Added an attention check item to the reviewer checklists (resolving issue #149). The item is placed randomly near the middle of the checklist and adds a note to the editor in the exported file if failed.
=> Attention check

assets/css/style.scss, form_generator/css/appearance.css, form_generator/index.html, form_generator/js/RequirementsChecklist.js, index.md
Re-added the open-close functionality for non-essential checklists + several small improvements to spacing
=> Small style fixes on home page and checklists

docs/standards/Experiments.md
A payoff function is a well-designed incentivization scheme for financial incentives, allowing to customize payouts based on participants’ performance/decisions and thereby mimicking the real world and motivating participants to spent effort.
=> Update Experiments.md for extraordinary attributes

docs/standards/MixedMethods.md, form_generator/css/appearance.css, form_generator/js/FormValidity.js, form_generator/js/RequirementsChecklist.js
Moved "clear checklist" button and made various fixes to exported file layout (valid item text between parentheses no longer incorrectly removed, sub-bullet items now indented, etc.)
=> Visual fixes

docs/supplements/OpenScience.md
Pursuant to #160, this PR adds references to artifacts for several of the method types in the Empirical Standards.
Credit: @KALU-KELECHI-GABRIEL 
CC @ctreude
=> Add exemplar artifacts aligned with standards
